#!/usr/bin/env sh

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
FONT="MesloLGS NF"

sketchybar --bar\
      height=39\
      shadow=off\
      position=top\
      sticky=on\
      color=0xff000000\

sketchybar --default\
  updates=when_shown\
  icon.font="$FONT:Bold:14.0"\
  label.font="$FONT:Regular:11.0"\
  label.padding_left=4\
  label.padding_right=4\

sketchybar --add item clock right\
   --set clock script="$PLUGIN_DIR/clock.sh" update_freq=1

sketchybar --add item battery right\
  --set battery script="$PLUGIN_DIR/battery.sh" update_freq=30


# The below command is only needed at the end of the initial configuration and
# should never be run in an item script.

sketchybar --update

echo "sketchybar configuration loaded.."
